version: '3.8'

services:
  # PostgreSQL 16 Database
  db:
    image: postgres:16-alpine
    container_name: uytop-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD_IS_REQUIRED}
      POSTGRES_DB: ${DB_NAME:-uytop_db}

    volumes:
      - uytop_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 7 In-Memory Cache & Rate Limiter
  redis:
    image: redis:7.2-alpine
    container_name: uytop-redis
    restart: unless-stopped

    volumes:
      - uytop_redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Core API Backend
  api:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.api
    container_name: uytop-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:?DB_PASSWORD_IS_REQUIRED}
      DB_NAME: ${DB_NAME:-uytop_db}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET_IS_REQUIRED}

  # Next.js App Router Web Frontend
  web:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.web
    container_name: uytop-web
    restart: unless-stopped
    depends_on:
      - api
    environment:
      NODE_ENV: production
      PORT: 3000
      API_INTERNAL_URL: http://api:4000/api/v1
      NEXT_PUBLIC_SITE_URL: http://localhost
      NEXT_PUBLIC_YANDEX_MAP_KEY: f3306db0-3796-48a0-8a47-f7037f6a73c1
    ports:
      - "3000:3000"

  # Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: uytop-nginx
    restart: unless-stopped
    depends_on:
      - web
      - api
    ports:
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  uytop_pgdata:
  uytop_redisdata:
